---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: aws-load-balancer-controller
      version: ">=1.0.8 <2.0.0"
      sourceRef:
        kind: HelmRepository
        name: eks
        namespace: flux-system
      interval: 30m
  values:
    clusterName: demo
