apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-node-termination-handler
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: aws-node-termination-handler
      version: ">=0.13.0 <1.0.0"
      sourceRef:
        kind: HelmRepository
        name: eks
        namespace: flux-system
      interval: 30m
