---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: autoscaler
  namespace: flux-system
spec:
  url: https://kubernetes.github.io/autoscaler
  interval: 30m

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cluster-autoscaler
      version: ">=9.1.0 <10.0.0"
      sourceRef:
        kind: HelmRepository
        name: autoscaler
        namespace: flux-system
      interval: 30m
  values:
    autoDiscovery:
      clusterName: demo
    extraArgs:
      v: 1
      logtostderr: true
      leader-elect: true
      write-status-configmap: true
      skip-nodes-with-system-pods: false
      skip-nodes-with-local-storage: false
