---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nginx
  namespace: flux-system
spec:
  url: https://helm.nginx.com/stable
  interval: 30m

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: nginx-ingress
      version: ">=0.7.1 <1.0.0"
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: flux-system
      interval: 30m
  values:
    autoDiscovery:
      clusterName: demo
